# Generated by Django 2.2.2 on 2019-06-27 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0002_paste_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paste',
            name='author',
        ),
    ]
