# Generated by Django 2.2.3 on 2019-07-04 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0007_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
