# Generated by Django 2.2.3 on 2019-07-05 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0009_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='allowed',
            field=models.CharField(blank=True, choices=[('yasser', 'yasser'), ('yasser2', 'yasser2')], max_length=200, null=True),
        ),
    ]
