# Generated by Django 2.2.3 on 2019-07-05 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0010_test_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='paste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='pastes.Paste'),
        ),
    ]
