# Generated by Django 2.2.3 on 2019-07-05 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0011_test_paste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='paste',
        ),
        migrations.AddField(
            model_name='paste',
            name='allow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pastes.Test'),
        ),
    ]
