# Generated by Django 2.2.3 on 2019-07-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0012_auto_20190705_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paste',
            name='allow',
        ),
        migrations.AddField(
            model_name='paste',
            name='allow',
            field=models.ManyToManyField(to='pastes.Test'),
        ),
    ]
