# Generated by Django 2.2.3 on 2019-07-05 14:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0013_auto_20190705_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paste',
            name='author',
        ),
        migrations.AlterField(
            model_name='paste',
            name='allow',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='test',
            name='allowed',
            field=models.CharField(blank=True, choices=[('yasser', 'yasser'), ('yasser2', 'yasser2'), ('yasser3', 'yasser3'), ('yasser4', 'yasser4')], max_length=200, null=True),
        ),
    ]
