# Generated by Django 2.2.3 on 2019-07-06 02:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0015_auto_20190706_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='allow',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='paste',
            name='author',
        ),
        migrations.AddField(
            model_name='paste',
            name='author',
            field=models.CharField(default='anonymous', max_length=100),
        ),
    ]
