# Generated by Django 2.2.3 on 2019-07-06 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0016_auto_20190706_0412'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
