# Generated by Django 2.2.3 on 2019-07-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0017_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='privacy',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
